[expose:data_dictionary_ping]
pattern = data_dictionary/ping
methods = GET

[expose:discovery_indexes]
pattern = data_dictionary/discovery/indexes
methods = GET

[expose:discovery_sourcetypes]
pattern = data_dictionary/discovery/sourcetypes
methods = GET

[expose:discovery_catalog]
pattern = data_dictionary/discovery/catalog
methods = GET

[expose:metadata]
pattern = data_dictionary/metadata
methods = GET, POST

[expose:metadata_key]
pattern = data_dictionary/metadata/*
methods = GET, POST, PUT, DELETE

[expose:options]
pattern = data_dictionary/options
methods = GET

[expose:dictionary_index]
pattern = data_dictionary/dictionary/index/*
methods = GET

[expose:dictionary_query]
pattern = data_dictionary/dictionary/query
methods = GET

[expose:build_catalog]
pattern = data_dictionary/build-catalog
methods = GET, POST
