[view_data_dictionary_metadata]
display_location = both
fields = index, sourcetype
label = View Metadata in Data Dictionary
link.method = get
link.target = blank
link.uri = /app/data_dictionary/home?index=$index$&sourcetype=$sourcetype$
type = link
